tpspam/config/urls.py
from django.contrib import admin
from django.urls import path, include
from spam import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('spam/', include('spam.urls')),
]

tpspam/spam/urls.py
from django.urls import path
from . import views

app_name = 'spam'

urlpatterns = [
    path('', views.index, name='index'),
    path('<int:question_id>/', views.detail, name='detail'),
    path('answer/create/<int:question_id>/', views.answer_create, name='answer_create'),
    path('question/create/', views.question_create, name='question_create'),
    path('delete-request/<int:question_id>/', views.delete_request, name='delete_request'),

]

tpspam/spam/models.py
from django.db import models

class Question(models.Model):
    subject = models.CharField(max_length=200)
    content = models.TextField()
    create_date = models.DateTimeField()

    def __str__(self):
        return self.subject

class Answer(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    content = models.TextField()
    create_date = models.DateTimeField()

tpspam/spam/forms.py
from django import forms
from spam.models import Question


class QuestionForm(forms.ModelForm):
    class Meta:
        model = Question
        fields = ['subject', 'content']
        labels = {
            'subject': '번호',
            'content': '내용',
        }

tpspam/spam/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.utils import timezone

from .forms import QuestionForm
from .models import Question

def answer_create(request, question_id):
    """
    spam 댓글 등록
    """
    question = get_object_or_404(Question, pk=question_id)
    question.answer_set.create(content=request.POST.get('content'), create_date=timezone.now())
    return redirect('spam:detail', question_id=question.id)

def index(request):
    """
    전화번호 출력
    """
    question_list = Question.objects.order_by('-create_date')
    context = {'question_list' : question_list}
    return render(request, 'spam/question_list.html', context)

def detail(request, question_id):
    """
    발신자 정보 출력
    """
    question = get_object_or_404(Question, pk=question_id)
    context = {'question': question}
    return render(request, 'spam/question_detail.html', context)

def question_create(request):
    """
    번호 등록
    """
    if request.method == 'POST':
        form = QuestionForm(request.POST)
        if form.is_valid():
            question = form.save(commit=False)
            question.create_date = timezone.now()
            question.save()
            return redirect('spam:index')
    else:
        form = QuestionForm()
    context = {'form': form}
    return render(request, 'spam/question_form.html', context)

from django.shortcuts import render, get_object_or_404
from .models import Question

def delete_request(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    # 필요한 로직을 구현하고 삭제요청 페이지를 렌더링하는 코드 작성

    return render(request, 'spam/delete_request.html', {'question': question})

tpspam/templates/base.html
{% load static %}
<!doctype html>
<html lang="ko">
<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <!-- Bootstrap CSS -->
    <link rel="stylesheet" type="text/css" href="{% static 'bootstrap.min.css' %}">
    <!-- pybo CSS -->
    <link rel="stylesheet" type="text/css" href="{% static 'style.css' %}">
    <title>Hello, pybo!</title>
</head>
<body>
<!-- 기본 템플릿 안에 삽입될 내용 Start -->
{% block content %}
{% endblock %}
<!-- 기본 템플릿 안에 삽입될 내용 End -->
</body>
</html>

tpspam/templates/spam/question_detail.html
{% extends 'base.html' %}

{% block content %}
<div class="container my-3">
    <h2 class="border-bottom py-2">{{ question.subject }}</h2>
    <div class="card my-3">
        <div class="card-body">
            <div class="card-text" style="white-space: pre-line;">{{ question.content }}</div>
            <div class="d-flex justify-content-end">
                <div class="badge badge-light p-2">
                    {{ question.create_date }}
                </div>
            </div>
        </div>
    </div>
<div>
    <ul>
    {% for answer in question.answer_set.all %}
        <li>{{ answer.content }}</li>
    {% endfor %}
    </ul>
</div>

<form action="{% url 'spam:answer_create' question.id %}" method="post">
    {% csrf_token %}
    <textarea name="content" id="content" rows="15"></textarea>
    <input type="submit" value="댓글 등록">
</form>

<a href="{% url 'spam:delete_request' question.id %}" class="btn btn-danger">번호 삭제</a>

{% endblock %}

tpspam/templates/spam/question_form.html
{% extends 'base.html' %}
{% block content %}
<div class="container">
    <h5 class="my-3 border-bottom pb-2">번호 등록</h5>
    <form method="post" class="post-form my-3">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit" class="btn btn-primary">저장하기</button>
    </form>
</div>
{% endblock %}

tpspam/templates/spam/question_list.html
{% extends 'base.html' %}

{% block content %}
    {% if question_list %}
        <ul>
        {% for question in question_list %}
            <li>
                <a href="{% url 'spam:detail' question.id %}">{{ question.subject }}</a>
                {% if question.answer_set.count > 0 %}
                    <span class="text-danger small ml-2">{{ question.answer_set.count }}</span>
                {% endif %}
            </li>
        {% endfor %}
        </ul>
    {% else %}
        <p>번호가 없습니다.</p>
    {% endif %}

    <a href="{% url 'spam:question_create' %}" class="btn btn-primary">번호 등록하기</a>
{% endblock %}